#!/usr/bin/env python3
"""Pack what `make build/samara.elf` needs into build/src.tar, a boot module
that unpacks to /usr/src/samaraos - so SamaraOS can rebuild its own kernel
with the gcc from build/gcc.tar:

    cd /usr/src/samaraos && make CROSS=/opt/gcc/bin/ -j1

Contents: Makefile, linker.ld, src/ (sources only), the doomgeneric sources,
the userland blobs the kernel embeds, and embed/*.wav. Plus /usr/bin/selfbuild:
build the kernel and store it as /mnt/samara.elf (the persistent disk), which
`make run` on the host boots when it is newer than its own build.
"""
import io, os, sys, tarfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "build/src.tar")
PREFIX = "usr/src/samaraos"
SRC_EXT = (".c", ".h", ".S", ".s", ".inc", ".ld")


def files():
    yield "Makefile"
    yield "linker.ld"
    for top in ("src", "doomgeneric-master/doomgeneric"):
        for dp, dn, fn in os.walk(os.path.join(ROOT, top)):
            dn.sort()
            for f in sorted(fn):
                if f.endswith(SRC_EXT) and f != "embed_list.h":   # generated by make
                    yield os.path.relpath(os.path.join(dp, f), ROOT)
    for f in ("src/gfx/termfont.bin", "userland/busybox", "userland/busybox.applets", "userland/sysroot.tar"):
        yield f
    ed = os.path.join(ROOT, "embed")
    for f in sorted(os.listdir(ed)) if os.path.isdir(ed) else []:
        if f.endswith(".wav"):
            yield "embed/" + f


SELFBUILD = r"""#!/bin/sh
# Rebuild the SamaraOS kernel inside SamaraOS with /opt/gcc and store it on
# the persistent disk (/mnt = disk.img), where `make run` on the host boots it.
cd /usr/src/samaraos || exit 1
echo "selfbuild: compiling the kernel (takes a while)..."
make CROSS=/opt/gcc/bin/ build/samara.elf "$@" || { echo "selfbuild: build failed"; exit 1; }
if ! grep -q " /mnt " /proc/mounts; then
    echo "selfbuild: no disk on /mnt - kernel left in /usr/src/samaraos/build/samara.elf"
    exit 1
fi
cp build/samara.elf /mnt/samara.elf && sync || { echo "selfbuild: copy failed"; exit 1; }
ls -l /mnt/samara.elf
echo "selfbuild: saved. On the host, 'make run' boots this kernel."
"""


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    dirs, n, size = set(), 0, 0
    with tarfile.open(OUT, "w", format=tarfile.USTAR_FORMAT) as tar:
        for d in ("usr", "usr/bin"):
            dirs.add(d)
            ti = tarfile.TarInfo(d)
            ti.type, ti.mode = tarfile.DIRTYPE, 0o755
            tar.addfile(ti)
        data = SELFBUILD.encode()
        ti = tarfile.TarInfo("usr/bin/selfbuild")
        ti.size, ti.mode = len(data), 0o755
        tar.addfile(ti, io.BytesIO(data))
        for rel in files():
            arc = f"{PREFIX}/{rel}"
            parts = arc.split("/")[:-1]
            for i in range(1, len(parts) + 1):
                d = "/".join(parts[:i])
                if d not in dirs:
                    dirs.add(d)
                    ti = tarfile.TarInfo(d)
                    ti.type, ti.mode = tarfile.DIRTYPE, 0o755
                    tar.addfile(ti)
            data = open(os.path.join(ROOT, rel), "rb").read()
            ti = tarfile.TarInfo(arc)
            ti.size, ti.mode = len(data), 0o644
            tar.addfile(ti, io.BytesIO(data))
            n += 1
            size += len(data)
    print(f"{OUT}: {n} files, {size >> 10} KiB")


if __name__ == "__main__":
    main()
