#!/usr/bin/env python3
"""
Rasterizes the desktop fonts into anti-aliased alpha atlases for SamaraOS
and writes src/gfx/uifont_data.h. The kernel has no TrueType renderer: the
glyphs are baked here on the host, indexed by CP866 byte (the encoding the
keyboard, terminal and browser already use), so Cyrillic just works.

  UI fonts   Golos Text (Paratype, SIL OFL 1.1) — proportional, 5 styles
  terminal   DejaVu Sans Mono (Bitstream Vera licence) — fixed 8x16 cells

Needs Pillow with FreeType:
  python3 -m venv toolchain/pyenv && toolchain/pyenv/bin/pip install pillow
  toolchain/pyenv/bin/python tools/mkfont.py
"""
import os
import sys
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "gfx", "uifont_data.h")

GOLOS = os.environ.get("GOLOS", "/usr/share/fonts/TTF/GolosText[wght].ttf")
MONO = os.environ.get("MONO", "/usr/share/fonts/TTF/DejaVuSansMono.ttf")

# CP866 bytes worth baking for text: ASCII, Cyrillic, Ёё/Єє/Її/Ўў, ° · √ № ¤.
# 0xB0..0xDF (box drawing) stay on the 8x16 VGA bitmap font.
TEXT_CODES = list(range(0x20, 0x7F)) + list(range(0x80, 0xB0)) + list(range(0xE0, 0x100))

# (C enum name, size px, weight, charset or None=TEXT_CODES)
UI_FONTS = [
    ("UIF_REG",   15, 400, None),
    ("UIF_MED",   15, 600, None),
    ("UIF_SMALL", 12, 500, None),
    ("UIF_BIG",   20, 700, None),
    ("UIF_HUGE",  84, 800, "samarOS"),   # desktop wordmark only
]

MONO_SIZE = 13
MONO_BASELINE = 12          # baseline row inside the 16px cell
CELL_W, CELL_H = 8, 16


def cp866(code):
    ch = bytes([code]).decode("cp866")
    return "\u00a0" if code == 0xFF else ch


def bake_ui(size, weight, charset):
    f = ImageFont.truetype(GOLOS, size)
    f.set_variation_by_axes([weight])
    ascent, descent = f.getmetrics()
    codes = TEXT_CODES if charset is None else sorted({c for c in charset.encode("cp866")} | {0x20})
    glyphs, data = {}, bytearray()
    for code in codes:
        ch = cp866(code)
        adv = int(round(f.getlength(ch) * 64))
        x0, y0, x1, y1 = f.getbbox(ch, anchor="ls")
        w, h = max(0, x1 - x0), max(0, y1 - y0)
        off = len(data)
        if w and h:
            img = Image.new("L", (w, h), 0)
            ImageDraw.Draw(img).text((-x0, -y0), ch, font=f, fill=255, anchor="ls")
            data += img.tobytes()
        glyphs[code] = (x0, y0 + ascent, w, h, adv, off)
    return ascent, descent, glyphs, data


def bake_mono():
    f = ImageFont.truetype(MONO, MONO_SIZE)
    present, data = [0] * 256, bytearray(256 * CELL_W * CELL_H)
    for code in TEXT_CODES:
        if code == 0xFF:
            continue
        img = Image.new("L", (CELL_W, CELL_H), 0)
        ImageDraw.Draw(img).text((0, MONO_BASELINE), cp866(code), font=f, fill=255, anchor="ls")
        data[code * CELL_W * CELL_H:(code + 1) * CELL_W * CELL_H] = img.tobytes()
        present[code] = 1
    return present, data


def c_bytes(buf, per_line=40):
    out = []
    for i in range(0, len(buf), per_line):
        out.append("    " + ",".join(str(b) for b in buf[i:i + per_line]) + ",")
    return "\n".join(out)


def main():
    lines = [
        "/* Generated by tools/mkfont.py — do not edit.",
        " * Golos Text (c) Paratype, SIL Open Font License 1.1.",
        " * DejaVu Sans Mono, Bitstream Vera / DejaVu licence. */",
        "#ifndef SAMARA_UIFONT_DATA_H",
        "#define SAMARA_UIFONT_DATA_H",
        "",
    ]
    faces = []
    for name, size, weight, charset in UI_FONTS:
        asc, desc, glyphs, data = bake_ui(size, weight, charset)
        sym = name.lower()
        lines.append(f"static const uint8_t {sym}_px[] = {{\n{c_bytes(data) or '    0,'}\n}};")
        lines.append(f"static const uif_glyph_t {sym}_gl[256] = {{")
        for code in sorted(glyphs):
            x, y, w, h, adv, off = glyphs[code]
            lines.append(f"    [{code}] = {{{x}, {y}, {w}, {h}, {adv}, {off}}},")
        lines.append("};")
        faces.append(f"    [{name}] = {{{asc}, {desc}, {sym}_gl, {sym}_px}},")
        print(f"{name}: {size}px w{weight} ascent={asc} descent={desc} "
              f"{len(glyphs)} glyphs, {len(data)} bytes", file=sys.stderr)
    lines.append("static const uif_face_t uif_faces[UIF_COUNT] = {")
    lines += faces
    lines.append("};")

    present, mono = bake_mono()
    lines.append(f"#define UIF_MONO_W {CELL_W}\n#define UIF_MONO_H {CELL_H}")
    lines.append("static const uint8_t uif_mono_have[256] = {\n" + c_bytes(present, 64) + "\n};")
    lines.append("static const uint8_t uif_mono_px[] = {\n" + c_bytes(mono) + "\n};")
    lines.append("")
    lines.append("#endif")
    with open(OUT, "w") as fp:
        fp.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({os.path.getsize(OUT) // 1024} KiB)", file=sys.stderr)


if __name__ == "__main__":
    main()
